#!/bin/sh
# validate-all-certs - GnuPG import and validate tests       -*- sh -*-
# Copyright (C) 2004, 2008 Free Software Foundation, Inc.  
#
# This file is part of GnuPG.
# 
# GnuPG is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# GnuPG is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

. ${srcdir:-.}/common.sh || exit 2

section=6
description="GnuPG Import with Validation"
info "Running $description tests"

while read dummy flag section name; do 
    case $dummy in \#*) continue;; esac
    [ -z "$(echo $dummy)" ] && continue;

    description="import and validate $name"
    if ${GPGSM} -q --import --with-validation --disable-crl-checks \
             certs/$name ; then
        if [ "$flag" = 'p' ]; then
            pass "validating certificate \`$name' succeeded"
        elif [ "$flag" = 'f' ]; then
            fail "validating certificate \`$name' succeeded"
        elif [ "$flag" = '?' ]; then
            unresolved "validating certificate \`$name' succeeded"
        elif [ "$flag" = 'u' ]; then
            skip "validating certificate \`$name' succeeded"
        else
            info "validating certificate \`$name' succeeded - (flag=$flag)"
        fi
    else
        if [ "$flag" = 'p' ]; then
            fail "validating certificate \`$name' failed"
        elif [ "$flag" = 'f' ]; then
            pass "validating certificate \`$name' failed"
        elif [ "$flag" = '?' ]; then
            unresolved "validating certificate \`$name' failed"
        elif [ "$flag" = 'u' ]; then
            skip "validating certificate \`$name' failed"
        else
            info "validating certificate \`$name' failed - (flag=$flag)"
        fi
    fi
done < $srcdir/import-all-certs.data

final_result
