@c Copyright (C) 2002 Free Software Foundation, Inc.
@c This is part of the GnuPG manual.
@c For copying conditions, see the file gnupg.texi.

@node Contributors
@unnumbered Contributors to GnuPG
@cindex contributors

The GnuPG project would like to thank its many contributors.  Without
them the project would not have been nearly as successful as it has
been.  Any omissions in this list are accidental.  Feel free to contact
the maintainer if you have been left out or some of your contributions
are not listed.  Please keep this list in alphabetical order.

@itemize @bullet

@item
Bernhard Herzog did extensive testing and tracked down a lot of bugs

@item
Bernhard Reiter made sure that we met the specifications and the
deadlines.  He did extensive testing and came up with a lot of suggestions.

@item
Jan-Oliver Wagner made sure that we met the specifications and the
deadlines.  He did extensive testing and came up with a lot of suggestions.

@item
Karl-Heinz Zimmer had to struggle with all the bugs and misconceptions
while working on Kmail integration.

@item
Marcus Brinkman cleaned up the Assuan code and fixed bugs all over the place.

@item
Steffen Hansen had a hard time to write the dirmngr due to
underspecified interfaces.

@item
Thomas Koester did extensive testing and tracked down a lot of bugs

@item
Werner Koch desgned the system and wrote most of the original code.

@end itemize

FIXME: We need to copy a lot of credits from GnupG 1.0 to here.


We'd also like to thank the folks who have contributed time and energy in
testing GnuPG:

@itemize @bullet
@item
Joe R. Hacker

@item
And many others
@end itemize

And finally we'd like to thank everyone who uses these tools, submits
bug reports and generally reminds us why we're doing this work in the
first place.
