@c Copyright (C) 2004 Free Software Foundation, Inc.
@c This is part of the GnuPG manual.
@c For copying conditions, see the file gnupg.texi.

@node Glossary
@unnumbered Glossary


@table @samp
@item ARL
      The @emph{Authority Revocation List} is technical identical to a
@acronym{CRL} but used for @acronym{CA}s and not for end user
certificates.

@item CRL
     The @emph{Certificate Revocation List} is a list containing
certificates revoked by the issuer.

@item CSR
     The @emph{Certificate Signing Request} is a message send to a CA to
ask them to issue a new certificate.  The data format of such a signing
request is called PCKS#10.

@item Keygrip
      This term is used by GnuPG to describe a 20 byte hash value used
to identify a certain key without referencing to a concrete protocol.
It is used internally to access a private key.  Usually it is shown and
entered as a 40 character hexadecimal formatted string.

@item OCSP
      The @emph{Online Certificate Status Protocol} is used as an
alternative to a @acronym{CRL}.  It is described in @code{RFC 2560}.

@item PSE
      The @emph{Personal Security Environment} describes a database to
store private keys.  This is either a smartcard or a collection of files
on a disk; the latter is often called a Soft-PSE.


@end table
