.TH GNUPG 7 2002-09-02 GNU "GNU Privacy Guard" 
.SH NAME
GnuPG \- The GNU Privacy Guard suite of programs
.SH DESCRIPTION
GnuPG is a set of programs for public key encryption and digital
signatures.  The program most users will want to use is the OpenPGP
command line tool, named \fBgpg\fP.  \fBgpgv\fP is a stripped down
version of \fBgpg\fP with no encryption functionality, used only to
verify signatures against a trusted keyring.  There is also a tool
called \fBgpgsplit\fP to split OpenPGP messages or keyrings into their
component packets.  This is mainly useful for seeing how OpenPGP
messages are put together.
.SH "SEE ALSO"
.BR gpg (1),
.BR gpgv (1),
