@c Copyright (C) 2004 Free Software Foundation, Inc.
@c This is part of the GnuPG manual.
@c For copying conditions, see the file gnupg.texi.

@node Invoking GPG
@chapter Invoking GPG
@cindex GPG command options
@cindex command options
@cindex options, GPG command

@c man begin DESCRIPTION

@command{gpg} is the OpenPGP part of GnuPG.  The version included in
this package is not as matured as the standard versions (1.2.x or
1.4.x) and thus we strongly suggest to keep on using the one of the
standard versions.  Both versions may be installed side by side and
should coexists without problems.  To help for that, the @command{gpg}
from this package gets installed under the name @command{gpg2}. If you
really want to use this @command{gpg2} command you should name the
configuration file @file{gpg.conf-1.9} to keep it separate from the
one used with the standard @command{gpg}.

Documentation for the old standard @command{gpg} is available in a
man page and at @inforef{Top,GnuPG 1,gpg}.


@c man end
