\input texinfo
@setfilename gpgv.info
@dircategory GnuPG
@direntry
* gpgv: (gpgv).                       GnuPG signature verification tool.
@end direntry

@node Top, , , (dir)
@top gpgv
@chapheading Name

gpgv --- signature verification tool
@chapheading Synopsis

@example
gpgv
 options
 signed files
  
@end example
@chapheading DESCRIPTION

@code{gpgv} is the OpenPGP signature checking tool.

This program is a stripped down version of @code{gpg} which is only
able
to check signatures. It is somewhat smaller than the full blown
@code{gpg} and uses a different (and more simple way) to check that
the public keys used to made the signature are trustworth. There is
no options files and only very few options are implemented.

@code{gpgv} assumes that all keys in the keyring are trustworty.
It uses by default a keyring named @file{trustedkeys.gpg} which is
assumed to be in the home directory as defined by GnuPG or set by an
option or an environment variable. An option may be used to specify
another keyring or even multiple keyrings.
@chapheading OPTIONS

@code{gpgv} recognizes these options:

@table @asis

@item -v, --verbose
Give more information during processing. If used
twice, the input data is listed in detail.

@item -q, --quiet
Try to be as quiet as possible.

@item --keyring @code{file}
Add @code{file} to the list of keyrings.
If @code{file} begins with a tilde and a slash, these
are replaced by the HOME directory. If the filename
does not contain a slash, it is assumed to be in the
home-directory ("~/.gnupg" if --homedir is not used).
The filename may be prefixed with a scheme:

"gnupg-ring:" is the default one.

@item --homedir @code{directory}
Set the name of the home directory to @code{directory} If this
option is not used it defaults to "~/.gnupg". It does
not make sense to use this in a options file. This
also overrides the environment variable "GNUPGHOME".

@item --status-fd @code{n}
Write special status strings to the file descriptor @code{n}.
See the file DETAILS in the documentation for a listing of them.

@item --logger-fd @code{n}
Write log output to file descriptor @code{n} and not to stderr.

@item --ignore-time-conflict
GnuPG normally checks that the timestamps associated with keys and
signatures have plausible values. However, sometimes a signature seems to
be older than the key due to clock problems. This option makes these
checks just a warning.
@end table
@chapheading RETURN VALUE

The program returns 0 if everything was fine, 1 if at least
one signature was bad, and other error codes for fatal errors.
@chapheading EXAMPLES

@table @asis

@item gpgv @code{pgpfile}
@itemx gpgv @code{sigfile} 
Verify the signature of the file. The second form
is used for detached signatures, where @code{sigfile} is the detached
signature (either ASCII armored or binary) and are the signed
data; if this is not given the name of the file holding the signed data is
constructed by cutting off the extension (".asc", ".sig" or ".sign") from
@code{sigfile}.
@end table
@chapheading ENVIRONMENT

@table @asis

@item HOME
Used to locate the default home directory.

@item GNUPGHOME
If set directory used instead of "~/.gnupg".
@end table
@chapheading FILES

@table @asis

@item ~/.gnupg/trustedkeys.gpg
The default keyring with the allowed keys
@end table

@bye
