#!/bin/sh

set -e

case "$1" in
       configure|abort-upgrade|abort-remove|abort-deconfigure)
	    if [ -x /usr/sbin/suidregister ]; then
		suidregister -s gpg /usr/bin/gpg root root 4755
	    else
		chmod 4755 /usr/bin/gpg
	    fi
            ;;
esac

