#!/bin/sh

set -e

case "$1" in
       purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	    if [ -x /usr/sbin/suidunregister ]; then
		suidunregister -s gpg /usr/bin/gpg
	    fi
	    ;;
esac
