#!/bin/sh
# mail a compressed version of the current translation to the Last-Translator
#

# remove the colon to armor this script.
SENDMAIL=": /usr/sbin/sendmail"

for file in *.po; do
    addr=$(head -100 $file | awk '/^# ?Designated-Translator:/ { printf "%s", $0; exit 0}' | sed 's/.*\(<.*>\).*/\1/')
    if [ -z "$addr" ]; then
    addr=$(awk '/Last-Translator:/ { printf "%s", $0; exit 0}' $file | sed 's/.*\(<.*>\).*/\1/')
    fi
    ll=$(basename $file .po)    

    if ! msgfmt -vc $file 2>&1| egrep -q 'fuzzy|untranslated|error'; then
        echo "$file: okay" >&2
        continue;
    fi    

    if ! echo "$addr" | grep -q @ ; then
        echo "$file: no translator known" >&2
        continue;
    fi

    echo "$file: sending to $addr"
    ( cat <<EOF
From: translations@gnupg.org
To: $addr
Mail-Followup-To: translations@gnupg.org
Subject: GnuPG translation ($ll)
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="=-=-="

--=-=-=

Hi!

Please find attached the very latest version of the PO file for your
GnuPG translation ($file). 

IMHO it is important to have a basic understanding of GnuPG's
functionality to do a correct translation.  A false translation might
need to security problems.  This is the reason why I prefer to contact
you directly and not to work only with the TP Robot.

Output of msgfmt is:
$(msgfmt --check --statistics $file 2>&1 | head)

If you are not able to continue the translation work, I suggest to
pass this message on to another translator and drop me a short note.

Thanks,

  Werner


--=-=-=
Content-Type: application/octet-stream
Content-Disposition: attachment; filename=gnupg-${file}.gz
Content-Transfer-Encoding: base64

EOF

gzip <$file | mimencode 

echo ""
echo "--=-=-=--"
echo ""
    ) | $SENDMAIL -oi "$addr"

done

