#!/bin/sh
# Copyright (C) 2002, 2004 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
if ! gpg --version > /dev/null 2>&1 ; then
   echo "GnuPG not available!"
   exit 1
fi

gpg="gpg --no-greeting --no-secmem-warning"

echo "This script converts your public keyring and trustdb from GnuPG"
echo "1.0.6 or earlier to the 1.0.7 and later format."

echo "If you have already done this, there is no harm (but no point)"
echo "in doing it again."

echo -n "Continue? (y/N)"

read answer

if test "x$answer" != "xy" ; then
  exit 0
fi

echo
echo "Marking your keys as ultimately trusted"
for key in `$gpg --with-colons --list-secret-keys | grep sec: | cut -d: -f5`
do
  $gpg --trusted-key $key --with-colons --list-keys $key > /dev/null 2>&1
  echo -n "."
done
echo

echo
echo "Adding signature caches"
$gpg --rebuild-keydb-caches

echo
echo "Checking trustdb"
$gpg --check-trustdb

echo
echo "Done!"
