#!/usr/bin/perl -w

# pgpgroup-to-gpggroup - convert PGP groups to GnuPG groups
# Copyright (C) 2004 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
# This program requires a PGP command line program that supports
# groups (note that the PGP 8 command line doesn't).

$pgp="pgp -gvv 2>/dev/null";

open(PGP,"$pgp|") || die "Unable to call PGP: $!";

while(<PGP>)
{
    # If the line begins with a ">", then it is a new group.

    if(/^ > (\S+)/)
    {
	print "\ngroup $1 = ";
    }
    elsif(/\s+(0x\S+)/)
    {
	print "$1 ";
    }
}

print "\n";
close(PGP);
