#!/bin/sh

if [ ! -f ./$1 ]; then
   echo "usage: signmany keyring" >&2
   exit 1
fi


ro="--trustdb-name=./tdb.tmp --no-default-keyring --secret-keyring /floppy/secring.gpg --keyring ./$1"

kis=`gpg $ro --fast-list-mode --list-keys --with-colons \
     | awk -F: '$1=="pub" { print $5 }'`

for k in $kis; do
    echo "Keyid: $k"
    answer=A
    while [ "$answer" = "A" ]; do
        gpg $ro --lock-never --no-interactive-selection --sign-key $k
        answer=""
        while [ "$answer" = "" ]; do
           read -p 'Okay, Again or Quit? (O/A/Q) '
           case "$REPLY" in
              o|O) answer=O ;;
              a|A) answer=A ;;
              q|Q) answer=Q ;;
              *) ;;
           esac
        done
    done
    [ "$answer" = "Q" ] && break
done

     
